export const equipments = [
  {
    title: "Nike Essential Ball Pump (Volt/Black)",
    desc: "Nike Essential Ball Pump (Volt/Black) ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKAC4354-753.jpg",
    currency: "INR ",
    price: "950",
    mrp: "950",
    discount: "0% off",
  },
  {
    title: "Nike Essential Ball Pump (Black/White)",
    desc: "Nike Essential Ball Pump (Black/White) ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKAC4354-027.jpg",
    currency: "INR ",
    price: "950",
    mrp: "950",
    discount: "0% off",
  },
  {
    title: "Stag Solid Steel Basketball Ring (18 Mm)",
    desc: "Stag Solid Steel Basketball Ring (18 mm) ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STABBRSS18.jpg",
    currency: "INR ",
    price: "1500",
    mrp: "1350",
    discount: "10% off",
  },
  {
    title: "Stag Hobby Solid Steel Basketball Ring (9mm)",
    desc: "Stag Hobby Solid Steel Basketball Ring (9mm) ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STABBRHB9.jpg",
    currency: "INR ",
    price: "750",
    mrp: "750",
    discount: "0% off",
  },
  {
    title: "Sklz Rapid Fire",
    desc: "The most convenient and effective basketball return system available gives players the ability to practice shooting repetitively from anywhere on the courtâ€”without chasing a ball. Return netting provides optimal height and flexible position for perfect ball returns to stay in rhythm. Like having your own rebounder, even for baseline shots. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/SZBBRF000.jpg",
    currency: "INR ",
    price: "13999",
    mrp: "11199",
    discount: "20% off",
  },
  {
    title: "Sklz Rain Maker",
    desc: "The Rain-Maker basketball shot trainer improves shooting accuracy and confidence by turning an 18â€ rim into a 15â€ rim. The tighter target forces the shooter to find the center of the hoop and find the perfect the arc on their shot. Includes a detachable â€œrejectorâ€ to allow for rebounding practice. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/SZBBRM00002.jpg",
    currency: "INR ",
    price: "3099",
    mrp: "2479",
    discount: "20% off",
  },
  // {
  //   title: "Stag Double Spring Basketball Ring With Net",
  //   desc: "Stag Double Spring Basketball Ring With Net ",
  //   img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
  //   currency: "INR ",
  //   price: "3200",
  //   mrp: "2880",
  //   discount: "10% off",
  // },
  // {
  //   title: "Stag Solid Steel Basketball Ring (20 Mm)",
  //   desc: "Stag Solid Steel Basketball Ring (20 mm) ",
  //   img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
  //   currency: "INR ",
  //   price: "2400",
  //   mrp: "2160",
  //   discount: "10% off",
  // },
];
