export const Shoes = [
  {
    name: "Nike Zoom Devosion Basketball Shoes (Black/Silver/Volt)",
    desc: "Nike Zoom Devosion Basketball Shoes (Black/Silver/Volt) ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK844592-002.jpg",
    currency: "INR ",
    mrp: "6495",
    sellingPrice: "6495",
    discount: "0% off",
  },
  {
    name: "Adidas 3 Series 2015 Basketball Shoes",
    desc: "Adidas 3 Series 2015 Basketball Shoes ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADBSS84964L.jpg",
    currency: "INR ",
    mrp: "6999",
    sellingPrice: "4899",
    discount: "30% off",
  },
  {
    name: "Nike Overplay VIII Basketball Shoes",
    desc: "Nike Overplay VIII Basketball Shoes ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK637382-107L.jpg",
    currency: "INR ",
    mrp: "4495",
    sellingPrice: "4495",
    discount: "0% off",
  },
  {
    name: "Adidas Next Level Speed Basketball Shoes",
    desc: "This cool adidas Next Level Speed basketball shoes for men are dedicated to keep the defense a step behind. Featuring rich materials, TORSIONÂ® stability and the addition of a cushioned GEOFITâ„¢ ankle collar for four-plus quarters of comfort, this is a perfect boot to rule over the court. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADBSS83650L.jpg",
    currency: "INR ",
    mrp: "6699",
    sellingPrice: "4689",
    discount: "30% off",
  },
  {
    name: "Nike Air Quick Handle Basketball Shoes",
    desc: "Nike Air Quick Handle Basketball Shoes ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "4595",
    sellingPrice: "4365",
    discount: "5% off",
  },
  {
    name: "Nike Prime Hype DF Basketball Shoes",
    desc: "Nike Prime Hype DF Basketball Shoes ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "6495",
    sellingPrice: "6495",
    discount: "0% off",
  },
  {
    name: "Nike Air Visi Pro VI Basketball Shoes",
    desc: "Nike Air Visi Pro VI Basketball Shoes ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "5795",
    sellingPrice: "5795",
    discount: "0% off",
  },
  {
    name: "Adidas D Lillard Basketball Shoes",
    desc: "Adidas D Lillard Basketball Shoes ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "9999",
    sellingPrice: "6999",
    discount: "30% off",
  },
  {
    name: "Adidas Isolation 2 Basketball Shoes (Grey/White)",
    desc: "Adidas Isolation 2 Basketball Shoes (Grey/White) ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "4999",
    sellingPrice: "3499",
    discount: "30% off",
  },
  {
    name: "Nike AIR Overplay IX Basketball Shoes (Black/White/Dark Grey)",
    desc: "Nike AIR Overplay IX Basketball Shoes (Black/White/Dark Grey) ",
    img: "https://martjackassets.blob.core.windows.net/css/storeui/images/show_loader.gif",
    currency: "INR ",
    mrp: "4995",
    sellingPrice: "4995",
    discount: "0% off",
  },
];
