export const Tables = [
  {
    name: "STAG PETER KARLSSON Automatic With Remote Controller Table Tennis Table",
    desc: "STAG PETER KARLSSON Automatic\nWith Remote Controller Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN20.jpg",
    currency: "INR ",
    mrp: "160000",
    sellingPrice: "143999",
    discount: "10% off",
  },
  {
    name: "STAG Elite 25 Table Tennis Table",
    desc: "STAG Elite 25 Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN151.jpg",
    currency: "INR ",
    mrp: "36000",
    sellingPrice: "32399",
    discount: "10% off",
  },
  {
    name: "STAG Elite 19 Table Tennis Table",
    desc: "STAG Elite 19 Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN153.jpg",
    currency: "INR ",
    mrp: "28000",
    sellingPrice: "25199",
    discount: "10% off",
  },
  {
    name: "STAG Hobby Line Table Tennis Table",
    desc: "STAG Hobby Line Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN190.jpg",
    currency: "INR ",
    mrp: "24500",
    sellingPrice: "24500",
    discount: "0% off",
  },
  {
    name: "STAG School Line Table Tennis Table",
    desc: "STAG School Line Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN200.jpg",
    currency: "INR ",
    mrp: "28500",
    sellingPrice: "25649",
    discount: "10% off",
  },
  {
    name: "STAG Fun Line Table Tennis Table",
    desc: "STAG Fun Line Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN210.jpg",
    currency: "INR ",
    mrp: "21000",
    sellingPrice: "21000",
    discount: "0% off",
  },
  {
    name: "STAG Family Weather Proof (CEN) Table Tennis Table",
    desc: "\nSuitable for Indoor & Outdoor use in home and garden. Extra strong playing surface giving good playability. Legs fold for storage. Two side wheels on each half for easy movement. Ready to play. CEN Certified. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB112W_L1.jpg",
    currency: "INR ",
    mrp: "31500",
    sellingPrice: "28349",
    discount: "10% off",
  },
  {
    name: "STAG Midi Table Tennis Table",
    desc: "\nFully assembled table with metallic legs and side wheels, recommended for kids 8 to 11 years. Ready to use and very useful training tool. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB109_L1.jpg",
    currency: "INR ",
    mrp: "13000",
    sellingPrice: "13000",
    discount: "0% off",
  },
  {
    name: "STAG Mini Table Tennis Table",
    desc: "\nFully assembled table with metallic legs, recommended for kids 8 to 11 years. Ready to use and very useful for training youth & children ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB104_L1.jpg",
    currency: "INR ",
    mrp: "10500",
    sellingPrice: "10500",
    discount: "0% off",
  },
  {
    name: "STAG Junior Table Tennis Table",
    desc: "\nRecommended for kids 5 to 8 years. Height adjustable to suit different players. Very useful training tool and ready to use. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB105_L1.jpg",
    currency: "INR ",
    mrp: "7900",
    sellingPrice: "7900",
    discount: "0% off",
  },
  {
    name: "STAG Elite Outdoor (CEN) Table Tennis Table",
    desc: "\nStylish and sleek with double locking device. Easily assembled with minimum storage space & modern looks. CEN Certified. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB122W_L1.jpg",
    currency: "INR ",
    mrp: "44000",
    sellingPrice: "39599",
    discount: "10% off",
  },
  {
    name: "STAG Outdoor Park Table Tennis Table",
    desc: "A strong and sturdy outdoor table. Can be fixed to the ground. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB126_L1.jpg",
    currency: "INR ",
    mrp: "42000",
    sellingPrice: "37799",
    discount: "10% off",
  },
  {
    name: "STAG Roll Away Table Tennis Table",
    desc: "\nVery Strong and sturdy table. Back Play possible. Galvanized & powder coated steel tube suitable for Outdoor & Indoor play. Revolutionary material for Table Top COMPREG. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB2000_L1.jpg",
    currency: "INR ",
    mrp: "54500",
    sellingPrice: "48999",
    discount: "10% off",
  },
  {
    name: "STAG Weather Proof Roll Away Table Tennis Table",
    desc: "\nRoll-away with 12 mm Compreg Top ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB107W_L1.jpg",
    currency: "INR ",
    mrp: "44000",
    sellingPrice: "39599",
    discount: "10% off",
  },
  {
    name: "STAG Sport Outdoor Table Tennis Table",
    desc: "Very Strong and sturdy table with modern looks. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB124W_L1.jpg",
    currency: "INR ",
    mrp: "39000",
    sellingPrice: "35099",
    discount: "10% off",
  },
  {
    name: "STAG Family (CEN) Table Tennis Table",
    desc: "\nCEN Certified with 16 mm top and 50 mm side wheels. Recommended for inhouse play. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB112_L1.jpg",
    currency: "INR ",
    mrp: "17500",
    sellingPrice: "17500",
    discount: "0% off",
  },
  {
    name: "STAG Ultimate Weather Proof Table Tennis Table",
    desc: "\nThe ultimate anti vandalism table for outdoor or indoor use based on special 18 mm compreg top. Can be fixed to ground. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB113W_L1.jpg",
    currency: "INR ",
    mrp: "73500",
    sellingPrice: "66149",
    discount: "10% off",
  },
  {
    name: "STAG Premium Outdoor Table Tennis Table",
    desc: "\nA designers delight ! Sturdy outdoor table with 12 mm Compreg top. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB125_L1.jpg",
    currency: "INR ",
    mrp: "58000",
    sellingPrice: "52199",
    discount: "10% off",
  },
  {
    name: "STAG Sleek Table Tennis Table",
    desc: "\nRoll-on with 16 mm top and 75 mm wheels. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB103_L1.jpg",
    currency: "INR ",
    mrp: "25000",
    sellingPrice: "25000",
    discount: "0% off",
  },
  {
    name: "STAG PETER KARLSSON Training Table Tennis Table",
    desc: "A good playable table with modern looks suitable for any playing area. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB121_L1.jpg",
    currency: "INR ",
    mrp: "31500",
    sellingPrice: "28349",
    discount: "10% off",
  },
  {
    name: "STAG PETER KARLSSON Table Tennis Table",
    desc: "\nAs Robust and stylish as the name PETER KARLSSON. This table with exceptional playing qualities is the latest addition to the exhaustive range of STAG table tennis tables. Suitable for high level competition and also an exclusive piece for any playing area. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB2010_L1.jpg",
    currency: "INR ",
    mrp: "83000",
    sellingPrice: "74699",
    discount: "10% off",
  },
  {
    name: "STAG Supreme Table Tennis Table",
    desc: "\nThis is a top end table from STAG. Massive and sturdy. Looks amazing, plays fantastic, smooth rolling, easy storage. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB2008_L1.jpg",
    currency: "INR ",
    mrp: "73000",
    sellingPrice: "65699",
    discount: "10% off",
  },
  {
    name: "STAG International Deluxe (ITTF) Table Tennis Table",
    desc: "\nThis table has been used in many international competitions including Asian Championships and Common Wealth Championships ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB1000Dx_L1.jpg",
    currency: "INR ",
    mrp: "52000",
    sellingPrice: "46799",
    discount: "10% off",
  },
  {
    name: "STAG Americas (ITTF) Table Tennis Table",
    desc: "\nVery Strong and sturdy table Approved by ITTF. Used in Championships in North America ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB2009_L1.jpg",
    currency: "INR ",
    mrp: "61000",
    sellingPrice: "54899",
    discount: "10% off",
  },
  {
    name: "STAG International (ITTF) Table Tennis Table",
    desc: "\nRecommended for National & International competitions ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB100_L1.jpg",
    currency: "INR ",
    mrp: "46000",
    sellingPrice: "41399",
    discount: "10% off",
  },
  {
    name: "STAG Championship (TTFI) Table Tennis Table",
    desc: "\nRoll-on with 75 mm Wheels and Leveler. TTFI approved. Recommended for Tournaments at Club, District & State levels. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB101_L1.jpg",
    currency: "INR ",
    mrp: "36500",
    sellingPrice: "32849",
    discount: "10% off",
  },
  {
    name: "STAG Club Table Tennis Table",
    desc: "\nRoll-on with 75mm wheels and levelers. Recommended for Club level and Schools ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTB102_L1.jpg",
    currency: "INR ",
    mrp: "31500",
    sellingPrice: "28349",
    discount: "10% off",
  },
  {
    name: "DONIC TEAM 303 Table Tennis Table",
    desc: "\nThis competition table is ideal for sports associations, schools and institutions! It has an 18 mm playing surface with movable 50 mm wheels.  ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB3L.jpg",
    currency: "INR ",
    mrp: "32299",
    sellingPrice: "32299",
    discount: "0% off",
  },
  {
    name: "DONIC TEAM 505 Table Tennis Table",
    desc: "\n18 mm table top and 75 mm wheels which are easily movable. Highest quality standards and Long lasting construction! ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB4L.jpg",
    currency: "INR ",
    mrp: "37999",
    sellingPrice: "37999",
    discount: "0% off",
  },
  {
    name: "DONIC TEAM 707 Table Tennis Table",
    desc: "\nThe ideal table with Outstanding Price : Performance ratio!\n19 mm table top, 75 mm wheels which are easily movable. Long lasting and highest quality standards.  ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB5L.jpg",
    currency: "INR ",
    mrp: "40499",
    sellingPrice: "40499",
    discount: "0% off",
  },
  {
    name: "DONIC WALDNER 909 Table Tennis Table",
    desc: "\nThis table has a 25 mm top and 100 mm wheels. Highest quality standard and modern design. Very comfortable handling. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB6L.jpg",
    currency: "INR ",
    mrp: "55949",
    sellingPrice: "55949",
    discount: "0% off",
  },
  {
    name: "DONIC CHAMPS 101 Table Tennis Table",
    desc: "\nThis table has a 16 mm playing surface with 50 mm wheels. Quick Release System. Easily movable wheels. ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB1L.jpg",
    currency: "INR ",
    mrp: "26399",
    sellingPrice: "26399",
    discount: "0% off",
  },
  {
    name: "DONIC CHAMPS 202 Table Tennis Table",
    desc: "\nThis table has a 16 mm playing surface with movable 50 mm wheels. Long-lasting construction with comfortable handling. Low storage space.  ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/DOTTTB2L.jpg",
    currency: "INR ",
    mrp: "28649",
    sellingPrice: "28649",
    discount: "0% off",
  },
  {
    name: "STAG Elite 22 Table Tennis Table",
    desc: "STAG Elite 22 Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN152.jpg",
    currency: "INR ",
    mrp: "32000",
    sellingPrice: "28799",
    discount: "10% off",
  },
  {
    name: "STAG Elite 16 Table Tennis Table",
    desc: "STAG Elite 16 Table Tennis Table ",
    img: "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/STATTTTIN154.jpg",
    currency: "INR ",
    mrp: "24000",
    sellingPrice: "24000",
    discount: "0% off",
  },
];
